cursor:allow_dumb_copy = true

env = AQ_DRM_DEVICES,/dev/dri/card0
env = WLR_DRM_DEVICES,/dev/dri/card0
env = AQ_FORCE_LINEAR_BLIT,0

misc:vfr = false # Disable variable refresh rate (VRR) if you experience stuttering or tearing

exec-once = sh -c 'notify-send "GPU Config" "WLR_DRM_DEVICES is set to: $WLR_DRM_DEVICES"'
exec-once = sh -c 'echo "Variable check: $WLR_DRM_DEVICES" > ~/hypr_check.txt'

